### ISSUE TITLE
question about setImmediate

### ISSUE THREAD

**Issue by unstoppablecarl** [majodev/metalsmith-data-markdown#2]
I have never used setImmediate.  After reading up on `setImmediate` It seems to make sense to use it here (I am not confident I understand exactly what it does without having used it). As far as I know there are no other metalsmith plugins that use this. 

Can you explain why you have it? or maybe why no one else has?

**Comment by majodev** [comment]
[`setImmediate`](http://nodejs.org/api/timers.html#timers_setimmediate_callback_arg) was used to yield a given function (`done()` in the case of metalsmith). Since metalsmith went to 1.0.0 recently, support for [Synchronous Plugins](https://github.com/segmentio/metalsmith/issues/87) was introduced and this behavior is actually no longer needed. 

However, I'm not quite sure if these statements should be dropped, as older metalsmith version might not work without it.

PS: The skeleton i used was quite the standard back then, e.g. [metalsmith-ignore](https://github.com/segmentio/metalsmith-ignore/blob/master/lib/index.js#L24) and [markdown](https://github.com/segmentio/metalsmith-markdown/blob/master/lib/index.js#L27) have `setImmediate` in it.
